### ISSUE TITLE
flood-fill

### ISSUE THREAD

**Issue by SHOBHA-0502** [ervikasji/Hacktoberfest2K22#11]
I want to add a solution to a very famous problem known as flood fill. this is a graph problem. which is commonly asked in interviews.
with proper explanation and code.

@ervikasji kindly assign this issue to me in hacktoberfest2022.

**Comment by vikastripathi707** [comment]
Make Pull Request and we will merge it.

**Comment by SHOBHA-0502** [comment]
sure
